id: AA2348808
base_file: f470C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:05:49.028396
  last_modified_at: 2022-05-30 21:05:49.028403
